/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayslipIndexRouteImport } from './routes/payslip/index'
import { Route as LeaveRequestIndexRouteImport } from './routes/leave-request/index'
import { Route as AssetsAssetsRouteImport } from './routes/assets/assets'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayslipIndexRoute = PayslipIndexRouteImport.update({
  id: '/payslip/',
  path: '/payslip/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRequestIndexRoute = LeaveRequestIndexRouteImport.update({
  id: '/leave-request/',
  path: '/leave-request/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsAssetsRoute = AssetsAssetsRouteImport.update({
  id: '/assets/assets',
  path: '/assets/assets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/test': typeof TestRoute
  '/assets/assets': typeof AssetsAssetsRoute
  '/leave-request': typeof LeaveRequestIndexRoute
  '/payslip': typeof PayslipIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/test': typeof TestRoute
  '/assets/assets': typeof AssetsAssetsRoute
  '/leave-request': typeof LeaveRequestIndexRoute
  '/payslip': typeof PayslipIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/test': typeof TestRoute
  '/assets/assets': typeof AssetsAssetsRoute
  '/leave-request/': typeof LeaveRequestIndexRoute
  '/payslip/': typeof PayslipIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/test'
    | '/assets/assets'
    | '/leave-request'
    | '/payslip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/test'
    | '/assets/assets'
    | '/leave-request'
    | '/payslip'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/test'
    | '/assets/assets'
    | '/leave-request/'
    | '/payslip/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TestRoute: typeof TestRoute
  AssetsAssetsRoute: typeof AssetsAssetsRoute
  LeaveRequestIndexRoute: typeof LeaveRequestIndexRoute
  PayslipIndexRoute: typeof PayslipIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payslip/': {
      id: '/payslip/'
      path: '/payslip'
      fullPath: '/payslip'
      preLoaderRoute: typeof PayslipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave-request/': {
      id: '/leave-request/'
      path: '/leave-request'
      fullPath: '/leave-request'
      preLoaderRoute: typeof LeaveRequestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/assets': {
      id: '/assets/assets'
      path: '/assets/assets'
      fullPath: '/assets/assets'
      preLoaderRoute: typeof AssetsAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TestRoute: TestRoute,
  AssetsAssetsRoute: AssetsAssetsRoute,
  LeaveRequestIndexRoute: LeaveRequestIndexRoute,
  PayslipIndexRoute: PayslipIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
